### ISSUE TITLE
Unable to add the reaction-cod in mac

### ISSUE THREAD

**Issue by hengsoheak** [Gouthamve/reaction-cod#13]
can not add this package to my reactioncommerce on mac os

`SOPHEAKs-MacBook-Pro:reaction sopheak$        
SOPHEAKs-MacBook-Pro:reaction sopheak$ meteor add gouthamve:reaction-cod 
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Potentially incompatible change required to top-level dependency: ongoworks:security
1.3.0, was 2.1.0.
Constraints on package "ongoworks:security":
* ongoworks:security@1.3.0 <- reactioncommerce:reaction-collections 1.0.4 <-
reactioncommerce:core 0.11.0 <- gouthamve:reaction-cod 1.2.0

To allow potentially incompatible changes to top-level dependencies, you must pass
--allow-incompatible-update on the command line.

SOPHEAKs-MacBook-Pro:reaction sopheak$ meteor add gouthamve:reaction-cod 2.1.0
 => Errors while parsing arguments:           
                                              
While adding package 2.1.0:
error: Package name must contain a lowercase ASCII letter: "2.1.0"

SOPHEAKs-MacBook-Pro:reaction sopheak$ meteor add gouthamve:reaction-cod "2.1.0"
 => Errors while parsing arguments:           
                                              
While adding package 2.1.0:
error: Package name must contain a lowercase ASCII letter: "2.1.0"

SOPHEAKs-MacBook-Pro:reaction sopheak$ meteor add gouthamve:reaction-cod 2.1.0 --allow-incompatible-update
 => Errors while parsing arguments:           
                                              
While adding package 2.1.0:
error: Package name must contain a lowercase ASCII letter: "2.1.0"
`

**Comment by gouthamve** [comment]
Hi, thanks for trying to use this, but I have made this a long while back and no longer maintain this package.
